---
#CIS hardening based on benchmark version 1.0.0
# CIS 2.1.1 Ensure /etc/xinetd.d/chargen services are not enabled
- name: "SCORED | 2.1.1 | PATCH | Ensure chargen services are not enabled | chargen-dgram,chargen-stream"
  block:
      - name: Ensure chargen services are not enabled | chargen-dgram
        stat:
            path: /etc/xinetd.d/chargen-dgram
        register: chargen_dgram_service

      - name: Ensure chargen services are not enabled | chargen-dgram
        command: chkconfig chargen-dgram off
        notify: restart xinetd
        when: chargen_dgram_service.stat.exists

      - name: Ensure chargen services are not enabled | chargen-stream
        stat:
            path: /etc/xinetd.d/chargen-stream
        register: chargen_stream_service

      - name: Ensure chargen services are not enabled | chargen-stream
        command: chkconfig chargen-stream off
        notify: restart xinetd
        when: chargen_stream_service.stat.exists
  become: true
  become_user: root

# CIS 2.1.2 Ensure daytime services are not enabled (Scored)
- name: Ensure daytime services are not enabled | daytime-dgram,daytime-stream
  block:
      - name: Ensure daytime services are not enabled | daytime-dgram
        stat:
            path: /etc/xinetd.d/daytime-dgram
        register: daytime_dgram_service

      - name: Ensure daytime services are not enabled | daytime-dgram
        command: chkconfig daytime-dgram off
        notify: restart xinetd
        when: daytime_dgram_service.stat.exists

      - name: Ensure daytime services are not enabled | daytime-stream
        stat:
            path: /etc/xinetd.d/daytime-stream
        register: daytime_stream_service

      - name: Ensure daytime services are not enabled | daytime-stream
        command: chkconfig daytime-stream off
        notify: restart xinetd
        when: daytime_stream_service.stat.exists
  become: true
  become_user: root

# CIS 2.1.3 Ensure discard services are not enabled (Scored)
- name: Ensure discard services are not enabled | discard-dgram,discard-stream
  block:
      - name: Ensure discard services are not enabled | discard-dgram
        stat:
            path: /etc/xinetd.d/discard-dgram
        register: discard_dgram_service

      - name: Ensure discard services are not enabled | discard-dgram
        command: chkconfig discard-dgram off
        notify: restart xinetd
        when: discard_dgram_service.stat.exists

      - name: Ensure discard services are not enabled | discard-stream
        stat:
            path: /etc/xinetd.d/discard-stream
        register: discard_stream_service

      - name: Ensure discard services are not enabled | discard-stream
        command: chkconfig discard-stream off
        notify: restart xinetd
        when: discard_stream_service.stat.exists
  become: true
  become_user: root

# CIS 2.1.4 Ensure echo services are not enabled (Scored)
- name: Ensure echo services are not enabled | echo-dgram,echo-stream
  block:
      - name: Ensure echo services are not enabled | echo-dgram
        stat:
            path: /etc/xinetd.d/echo-dgram
        register: echo_dgram_service

      - name: Ensure echo services are not enabled | echo-dgram
        command: chkconfig echo-dgram off
        notify: restart xinetd
        when: echo_dgram_service.stat.exists

      - name: Ensure echo services are not enabled | echo-stream
        stat:
            path: /etc/xinetd.d/echo-stream
        register: echo_stream_service

      - name: Ensure echo services are not enabled | echo-stream
        command: chkconfig echo-stream off
        notify: restart xinetd
        when: echo_stream_service.stat.exists
  become: true
  become_user: root

# CIS 2.1.5 Ensure time services are not enabled (Scored)
- name: Ensure time services are not enabled | time-dgram,time-stream
  block:
      - name: Ensure time services are not enabled | time-dgram
        stat:
            path: /etc/xinetd.d/time-dgram
        register: time_dgram_service

      - name: Ensure time services are not enabled | time-dgram
        command: chkconfig time-dgram off
        notify: restart xinetd
        when: time_dgram_service.stat.exists

      - name: Ensure time services are not enabled | time-stream
        stat:
            path: /etc/xinetd.d/time-stream
        register: time_stream_service

      - name: Ensure time services are not enabled | time-stream
        command: chkconfig time-stream off
        notify: restart xinetd
        when: time_stream_service.stat.exists
  become: true
  become_user: root

# CIS 2.1.6 Ensure rsh server is not enabled (Scored)
- stat:
    path: /etc/xinetd.d/rsh
  register: rsh_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  become: true
  become_user: root


- name: 2.1.6 Ensure rsh server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/rsh
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: rsh_file.stat.exists
  become: true
  become_user: root

# CIS 2.1.7 Ensure talk server is not enabled (Scored)
- stat:
    path: /etc/xinetd.d/talk
  register: talk_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  become: true
  become_user: root

- name: 2.1.7 Ensure talk server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/talk
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: talk_file.stat.exists
  become: true
  become_user: root

# CIS 2.1.8 Ensure telnet server is not enabled (Scored)
- stat:
    path: /etc/xinetd.d/telnet
  register: telnet_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  become: true
  become_user: root

- name: 2.1.8 Ensure telnet server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/telnet
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: telnet_file.stat.exists
  become: true
  become_user: root

# CIS 2.1.9 Ensure tftp server is not enabled (Scored)
- stat:
    path: /etc/xinetd.d/tftp
  register: tftp_file
  failed_when: False
  ignore_errors: True
  changed_when: False
  become: true
  become_user: root


- name: 2.1.9 Ensure tftp server is not enabled (Scored)
  lineinfile:
    dest: /etc/xinetd.d/tftp
    regexp: '^disable                = yes'
    line: 'disable           = yes'
  when: tftp_file.stat.exists
  become: true
  become_user: root

# CIS 2.1.9 Ensure tftp server is not enabled (Scored)
- command: dpkg -l xinetd
  register: xinetd_installed
  failed_when: False
  ignore_errors: True
  changed_when: False
  become: true
  become_user: root

# CIS 2.1.10 Ensure xinetd is not enabled (Scored)
- name: 2.1.10 Ensure xinetd is not enabled (Scored)
  systemd:
    name: xinetd
    state: stopped
  when: xinetd_installed.rc == 0
  become: true
  become_user: root

# Time synchronization task need ip of ntp server which make image evvironment dependent, this task will be done in later staps 
## CIS 2.2.1.1 Ensure time synchronization is in use (Not Scored)
#- name: 2.2.1.1 Ensure time synchronization is in use (Not Scored)
#  yum:
#    name: "{{rhel7cis_time_synchronization}}"
#    state: present
#  become: true
#  become_user: root
#
## CIS 2.2.1.2 Ensure ntp is configured (Scored)
#- name: 2.2.1.2 Ensure ntp is configured (Scored)
#  lineinfile:
#    dest: "{{ item.name }}"
#    regexp: '{{item.expression}}'
#    line: '{{item.value}}'
#  with_items:
#    - { name: '/etc/ntp.conf' , expression: '^server' , value: '10.124.12.10' }
#    - { name: '/etc/ntp.conf' , expression: '^restrict -4' , value: 'restrict -4 default kod nomodify notrap nopeer noquery' }
#    - { name: '/etc/ntp.conf' , expression: '^restrict -6' , value: 'restrict -6 default kod nomodify notrap nopeer noquery' }
#    - { name: '/etc/init.d/ntp', expression: '^RUNASUSER' , value: 'RUNASUSER=ntp' }
#  when: rhel7cis_time_synchronization  == "ntp" and Region == "us-flo" and Stage == "dev"
#  notify: restart ntp
#
## CIS 2.2.1.2 Ensure ntp is configured (Scored)
#- name: 2.2.1.2 Ensure ntp is configured (Scored)
#  lineinfile:
#    dest: "{{ item.name }}"
#    regexp: '{{item.expression}}'
#    line: '{{item.value}}'
#  with_items:
#    - { name: '/etc/ntp.conf' , expression: '^server' , value: '10.22.16.135' }
#    - { name: '/etc/ntp.conf' , expression: '^restrict -4' , value: 'restrict -4 default kod nomodify notrap nopeer noquery' }
#    - { name: '/etc/ntp.conf' , expression: '^restrict -6' , value: 'restrict -6 default kod nomodify notrap nopeer noquery' }
#    - { name: '/etc/init.d/ntp', expression: '^RUNASUSER' , value: 'RUNASUSER=ntp' }
#  when: rhel7cis_time_synchronization  == "ntp" and Region == "us-flo" and Stage == "prod"
#  notify: restart ntp
#
#
#
## currently we are not installing chrony
##CIS 2.2.1.3 Ensure chrony is configured (Scored)
#- name: 2.2.1.3 Ensure chrony is configured (Scored)
#  lineinfile:
#    dest: "{{ item.name }}"
#    regexp: '{{item.expression}}'
#    line: '{{item.value}}'
#  with_items:
# #   - { name: '/etc/chrony.conf', expression: '^server', value: "server {{ ntp_server_ip }}" }
#    - { name: '/etc/chrony.conf', expression: '^pool', value: '' }
#  when: rhel7cis_time_synchronization  == "chrony" and ntp_server_ip != ""
#  #notify: restart chrony
#  become: true
#  become_user: root
#
##CIS 2.2.1.3 Ensure chrony is configured (Scored)
#- name: 2.2.1.3 Ensure chrony is configured (Scored)
#  lineinfile:
#    dest: "/etc/chrony.conf"
#    #regexp: '^server'
#    line: 'server {{item}}'
#    insertafter: '^server'
#  with_items:
#    - "{{ ntp_server_ip }}" 
#  when: rhel7cis_time_synchronization  == "chrony" and ntp_server_ip != ""
#  #notify: restart chrony
#  become: true
#  become_user: root  

    
# CIS 2.2.2 Ensure X Window System is not installed (Scored)
- name: Ensure X Window System is not installed
  yum:
      name: "@X Window System"
      state: absent
  become: true
  become_user: root
  
# CIS 2.2.2 Ensure X Window System is not installed (Scored)
- name: Ensure X Window System is not installed
  yum:
      name: "xorg-x11*"
      state: absent
  become: true
  become_user: root
  
  

# CIS 2.2.3 Ensure Avahi Server is not enabled (Scored)
- name: Ensure Avahi Server is not enabled
  service:
      name: avahi-daemon
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.4 Ensure CUPS is not enabled (Scored)
- name: Ensure CUPS is not enabled
  service:
      name: cups
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.5 Ensure DHCP Server is not enabled (Scored)
- name: Ensure DHCP Server is not enabled
  service:
      name: dhcpd
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.6 Ensure LDAP server is not enabled (Scored)
- name: Ensure LDAP server is not enabled
  service:
      name: slapd
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.7 Ensure NFS and RPC are not enabled (Scored)
- name: Ensure NFS and RPC are not enabled
  service:
      name: nfs
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

- name: Ensure RPC is not enabled
  service:
      name: rpcbind
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.8 Ensure DNS Server is not enabled (Scored)
- name: Ensure DNS Server is not enabled
  service:
      name: named
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.9 Ensure FTP Server is not enabled (Scored)
- name: Ensure FTP Server is not enabled
  service:
      name: vsftpd
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.10 Ensure HTTP server is not enabled (Scored)
- name: Ensure HTTP server is not enabled
  service:
      name: httpd
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.11 Ensure IMAP and POP3 server is not enabled (Scored)
- name: Ensure IMAP and POP3 server is not enabled
  service:
      name: dovecot
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.12 Ensure Samba is not enabled (Scored)
- name: Ensure Samba is not enabled
  service:
      name: smb
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.13 Ensure HTTP Proxy Server is not enabled (Scored)
- name: Ensure HTTP Proxy Server is not enabled
  service:
      name: squid
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.14 Ensure SNMP Server is not enabled (Scored)
- name: Ensure SNMP Server is not enabled
  service:
      name: snmpd
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.15 Ensure mail transfer agent is configured for local-only mode (Scored)
- name: "SCORED | 2.2.15 | PATCH | Ensure mail transfer agent is configured for local-only mode"
  lineinfile:
      dest: /etc/postfix/main.cf
      regexp: "^(#)?inet_interfaces"
      line: "inet_interfaces = localhost"
  become: true
  become_user: root


# CIS 2.2.16 Ensure rsync service is not enabled (Scored)
- name: Ensure rsync service is not enabled
  service:
      name: rsyncd
      state: stopped
      enabled: no
  ignore_errors: True
  become: true
  become_user: root

# CIS 2.2.17 Ensure NIS Server is not enabled (Scored)

# CIS 2.3.1 Ensure NIS Client is not installed (Scored)
- name: Ensure NIS Client is not installed
  yum:
      name: ypbind
      state: absent
  become: true
  become_user: root

# CIS 2.3.2 Ensure rsh client is not installed (Scored)
- name: Ensure rsh client is not installed
  yum:
      name: rsh
      state: absent
  become: true
  become_user: root

# CIS 2.3.3 Ensure talk client is not installed (Scored)
- name: Ensure talk client is not installed
  yum:
      name: talk
      state: absent
  become: true
  become_user: root

# CIS 2.3.4 Ensure telnet client is not installed (Scored)
- name: Ensure telnet client is not installed
  yum:
      name: telnet
      state: absent
  become: true
  become_user: root

# CIS 2.3.5 Ensure LDAP client is not installed (Scored)
- name: Ensure LDAP client is not installed
  yum:
      name: openldap-clients
      state: absent
  become: true
  become_user: root
